name: Build and Deploy Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t myapp .

      - name: Tag Docker image
        run: docker tag myapp blackset/myapp:latest

      - name: Push Docker image to Docker Hub
        run: docker push blackset/myapp:latest
